openapi: 3.0.0
info:
  title: API joya SFR
  version: '1.0'
servers:
  - url: https://selfcare-webservices.sfr.fr/webservices/joya/services/rest/1.0
paths:
  '/joya/{msisdn}':
    parameters:
      - in: path
        name: msisdn
        required: true
        schema:
          type: string
    get:
      parameters:
        - in: query
          name: platform
          required: false
          schema:
            type: string
        - in: query
          name: callback
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successful Response
components:
  securitySchemes:
    casauthenticationtoken:
      type: apiKey
      in: header
      name: casauthenticationtoken
      description: Jeton temporaire d'authentification
security:
  - casauthenticationtoken: []